### ISSUE TITLE
Returning 1 from a rawt bind doesn't prevent eggdrop from processing the message

### ISSUE THREAD

**Issue by DasBrain** [eggheads/eggdrop#1164]
> RAWT Return 1 to ask the bot not to process the server text. This can affet the bot’s performance by causing it to miss things that it would normally act on – you have been warned. Again.

Contrary to this statement in the documentation, eggdrop still processes and acts upon messages where a bind has returned 1.

I need this functionality to prevent eggdrop from acting upon the channel history (often channel-mode +H).  
I use the [batch] IRCv3 capability to determine if a PRIVMSG or NOTICE are part of the channel history and return 1 for the bot to ignore that: https://github.com/DasBrain/brain-tools/blob/master/dasbrain/ignorechathistory-1.0.tm

[batch]: https://ircv3.net/specs/extensions/batch

**Comment by vanosg** [comment]
The issue- In the current codebase, The call to RAW needs to be blocked as well as RAWT; ideally there's an easy way to block both (ha) when returning a 1 from one of them....

**Comment by thommey** [comment]
The call order is rawt -> raw (before stripping msgtags -> after stripping msgtags) with rawt being truer to the original input we received. So that call order makes sense. The implication is that a return 1 in rawt can block raw, but a return 1 in raw cannot block rawt. We should implement and document it that way nonetheless.
