### ISSUE TITLE
Eggdrop doesn't process account-tag (and maybe others) unless the message-tags capability has been negotiated.

### ISSUE THREAD

**Issue by DasBrain** [eggheads/eggdrop#1179]
When enabling a capability that uses tags but without negotiating the `message-tags` capability eggdrop won't process any tag message.

Eggdrop should process tag messages regardless if the `message-tags` capability has been negotiated or not.

**Comment by vanosg** [comment]
What/How are you expecting a tag message to be processed? What specifically does work that doesn't work without message-tags?

**Comment by vanosg** [comment]
Ah, I got confused by the wording- the title of "tag-message" made me think you were referring to TAGMSGs, but your IRC comment refers to the account-tag capability

**Comment by vanosg** [comment]
What is an example of a command that this applies to?

**Comment by vanosg** [comment]
@DasBrain we hope to use your input to consider this for 1.9.2, but the window to do some before we release is closing. If you can provide an example in the near future so we can better understand the use case, it would be much appreciated.  Thanks!

**Comment by DasBrain** [comment]
Request the `account-tag` capability on libera.chat. (`.tcl cap req account-tag`).

Eggdrop will stop responding to any message from a logged in user.

**Comment by vanosg** [comment]
Thanks- and not to beat a dead horse, but what type of message does Eggdrop not respond to? Public text via a bind, for example? Commands sent via message? or something more specialized? Thanks

**Comment by vanosg** [comment]
OK, I see what you mean- any public message sent by the user is ignored.

So what I think is happening: Eggdrop receives the message from the user, but (I believe) because message-tag isn't enabled, Eggdrop doesn't know to look past the tags present in the message, gets confused, and discards every message. And we can't just request message-tag, because servers like Libera support account-tag, but not message-tag. message-tag implies not just that the server supports tags, but rather that ANY tag can be sent. account-tag can still, per the slightly ambiguous spec, legally be sent without message-tag being enabled.

**Comment by DasBrain** [comment]
> because message-tag isn't enabled, Eggdrop doesn't know to look past the tags present in the message, gets confused, and discards every message

Yes, exactly: https://github.com/eggheads/eggdrop/blob/d2acc5fe4babbfc6cd5f8e7b5dd391d1e367e621/src/mod/server.mod/servmsg.c#L1150-L1151

Fix: Replace `if (msgtag)` with `if (1)`. 😉

**Comment by vanosg** [comment]
Same issue with extended-join

**Comment by DasBrain** [comment]
Extended Join only adds more parameters to the JOIN. But if you have account-tag activated, the JOIN will also contain message-tags - which eggdrop won't process, causing a desync. (MODE, KICK... should also contain the account tag)
