### ISSUE TITLE
Nat-ip returns 255.255.255.255 with invalid input

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#1181]
Found by: Fatale_gg

A user entered with ctcp chat issues after setting config file variable 'nat-ip' to a hostname. While the config file does state it takes an IP, at minimum an error should be thrown for invalid input. The specific issue results from using inet_addr (from the man page):

> The inet_addr() function converts the Internet host address cp from IPv4 numbers-and-dots notation into binary data in network byte order. If the input is invalid, INADDR_NONE (usually -1) is returned. Use of this function is problematic because -1 is a valid address (255.255.255.255). Avoid its use in favor of inet_aton(), inet_pton(3), or getaddrinfo(3) which provide a cleaner way to indicate error return. 

The task at minimum  here is to update from inet_addr to something more modern. Discussion could occur as to whether or not this setting should be upgraded to resolve a hostname- as a scenario:

A user on a home network is more likely to be NAT'd than a cloud/colo server. A home user is also more likely to on a dynamic IP rather than a static. A user may setup a dyndns-like service that is updated with the correct dynamic IP, and then try to use that hostname with nat-ip, so Eggdrop sends a proper IP after the IP changes.

**Comment by michaelortmann** [comment]
Thanks for finding this. I already did and planned some work on modernization of eggdrops use of inet functions like  gethostbyname2(). looks like i missed this one.

**Comment by michaelortmann** [comment]
**Testcase:**
eggdrop.conf:
`set nat-ip "testhostname"`
irc client:
```
/ctcp testbot chat
*** DCC CHAT (chat) request received from testbot [255.255.255.255:3333]
```
testbot:
`[11:23:53] CTCP CHAT:  from testuser (~michael@localhost)`

Due to design restrictions (we dont wanna break module or tcl API) we cant do async (unblocking) dns resolving for nat-ip for ctcp chat / dcc chat. We also dont want to continuously async resolve (and cache the result) nat-ip in mainloop. So we need to reject the idea to let eggdrop core resolve a (dyndns) hostname given via nat-ip.

**What we do now is:**

1. implement (and log / act on it) check for nat-ip is a valid IP

2. document (wiki?) that dyndns ctcp chat / dcc chat can be done by the user (or tcl) changing (setting) the already existing nat-ip to the new IP whenever the IP changes. This can be implemented in tcl, maybe using a dyndns update client. That event driven update is better than our core polling the resolver.

**More details:**

additionaly error checks and reports must be implemented:
currently the bot only logs:
`[11:23:53] CTCP CHAT:  from testuser (~michael@localhost)`
which doesnt help at all
maybe the bot should log the IP transmitted to the user

`255.255.255.255` must not be transmitted to the requesting client
instead of sending invalid IPs, errors must be detected, logged and no dcc chat request must be made
doc must be updated
to solve this issue, `net.c:getdccfamilyaddr()` must be changed and `inet_addr()` calls must be replaced, i think we need `getaddrinfo()` instead.

**Comment by michaelortmann** [comment]
We will use inet_pton() to solve this issue. its simple and posix 2001.
Log will go to LOG_MISC instead of lower level debug.
nat-ip will be checked also on eggdrop startup.
