### ISSUE TITLE
Functions for working with twitch users

### ISSUE THREAD

**Issue by sx66627** [eggheads/eggdrop#1194]
Good day
I am writing a bot for twitch (using twitch.mod) and found that it is not possible to get to check the status of a user (partner, broadcaster, etc.).
When calling pub/pubm, I can check for badges. But if I take the nickname from the list of users, then this is impossible. Exception ismod/isvip.
I would like the following versions to have such an opportunity.

Another feature is that all nicknames received from the bot ($nick) are indicated in lower case. I would like to be able to take display-name. Of course, this does not affect the work of the scripts in any way, but it will be aesthetically more beautiful :)
Example:
```
$nick == "ami_go_"
display_name == "Ami_Go_"
```

Thanks!

**Comment by vanosg** [comment]
I'm not a Twitch expert, but that information doesn't appear to be announced via the IRC gateway. There is no way to query a channel for who is who; that information is only made available if the user posts to the channel (ismod/isvip are the exceptions, which is why they exist as commands). There is no way to maintain a comprehensive or fully accurate list of these statuses. If anyone has an idea on how to do so, please share.

**Comment by sx66627** [comment]
I don't know if it will work, but you can check here and get the response in json: 
http://tmi.twitch.tv/group/user/[CHANNEL]/chatters

There is no such possibility by means of irc.
