### ISSUE TITLE
Investigate invalid nick process on registration

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#1201]
If an eggdrop joins a server and attempts to register with an invalid nick, it looks at keep-nick in the config. If keep-nick is enabled, it will not try another nickname and end up disconnecting. If keep-nick is not enabled, it will generate a random nickname to continue registration with.

The question was posed in channel, should Eggdrop try to use the $altnick nickname, instead of a random nickname?

After some thought, I think I would lean towards saying 'no', a random nick is fine in order to ensure you are able to connect to the server. But, I think a log message to the partyline indicating what is going on behind the curtain might help users who are expecting the nickname "##MYBOT##" to join a channel, but end up with the nickname "sifnhjlper" joining instead. And keep-nick controlling this functionality is not intuitive to check, so probably need to mention that somewhere in there, too.

Thoughts?

**Comment by ZarTek-Creole** [comment]
My idea is that if the nickname is invalid (or already in use) it should use the altnick. The default value of altnick should be changed to "????????" for a default random nickname.

\# Set the alternative nick which the bot uses on IRC _if the nick specified
\# by 'set nick' is unavailable_. **All '?' characters will be replaced by random
\# numbers.**
set altnick "Llamab?t"

The keep-nick should be used when the connection is successful and eggdrop uses altnick instead of nick.


My second think, if the nickname is invalid / illegal character nick an explicit error message should prevent its launch

**Comment by thommey** [comment]
keep-nick shouldn't change that behavior, it's not related to its function at all.

Trying altnick instead of a random nick makes a lot of sense, we can still fall back to a random nick if altnick *also* fails.

**Comment by vanosg** [comment]
keep-nick means, to me, try to get what is set if it is changed, and don't change away from it. I think that applies here as well, but I can see the opposing point that getting on the network is more important than keeping the requested nick.
