### ISSUE TITLE
"configure: WARNING: unrecognized options: --enable-tls, --enable-ipv6" when building modules

### ISSUE THREAD

**Issue by sbraz** [eggheads/eggdrop#1247]
Hi,
The current Makefile passes all parameters from `configure` to the module's `configure`:
https://github.com/eggheads/eggdrop/blob/d3083ccbed17e9663854d6c359fdb74f78c811ce/src/mod/Makefile.in#L89

This results in build-time warnings, for instance:
```
Configuring module 'compress'.
configure: WARNING: unrecognized options: --enable-tls, --enable-ipv6
configure: creating cache ../../../config.cache
```

Initially reported as https://bugs.gentoo.org/829087

**Comment by sbraz** [comment]
I'm being told this isn't such a big deal and we should just ignore those warnings. Apologies for the noise.

**Comment by vanosg** [comment]
Can you help me interpret what was posted to Gentoo? I can't tell if it is an issue with the way it is built for their package, or something else. I can't replicate this error on other OSs when compiling from the source. This may be indicative of a larger issue, but I can't tell if it is an Eggdrop issue, or a Gentoo packages issue. Can you compile from source on Gentoo and tell me if you see the same warning?

**Comment by sbraz** [comment]
Actually I can't reproduce it either any more on my Gentoo install. @thesamesam, do you know why? Do we pass a specific option to autotools?

**Comment by sbraz** [comment]
@vanosg OK got it, the culprit is `--enable-option-checking=warn`. You can reproduce the problem with `./configure --enable-tls --enable-option-checking=warn; make config`.

**Comment by thesamesam** [comment]
Apologies for the noise both! The bug is invalid and can be closed but it's my fault.

Summary:
In Gentoo, we have some automatic detection for build logs where we look for e.g. 'unrecognized argument: ...' for some reason, this doesn't always work even when packages lack subconfigure (net-misc/curl seems to be an example of this!)

I asked toralf to pass '--enable-option-checking=fatal' (he later changed it to 'warn') to help find some of those "curl-like: examples

The problem is that option *also affects* subconfigure (where you call configure for a mini project within your main one), which autoconf says unknown arguments are okay for (we don't care about this in gentoo obviously because autoconf says it's fine): https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Option-Checking.html

We need to understand why e.g. net-misc/curl is different: what is it doing differently? is it somehow disabling the normal warning?

(A lot of the bugs toralf filed are legit, curl-like cases, but some of them were false positives, like this eggdrop one (because of subconfigure).)

I'm sorry for the hassle!

**Comment by vanosg** [comment]
I'm glad we (well, you) solved it! But I was happy to cheerlead. if there is something we can do from this side, let me know. Thanks!
