### ISSUE TITLE
latest git pull not compiling - SSL?

### ISSUE THREAD

**Issue by Kelerion-UK** [eggheads/eggdrop#1282]
Making core eggdrop files...

make[1]: Entering directory '/home/ubuntu/eliza/src'
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include/tcl8.6 -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c botcmd.c
botcmd.c: In function ‘bot_nlinked’:
botcmd.c:726:53: error: ‘struct dcc_t’ has no member named ‘ssl’
  726 |   addbot(newbot, dcc[idx].nick, next, x, i, dcc[idx].ssl);
      |                                                     ^
make[1]: *** [Makefile:83: botcmd.o] Error 1
make[1]: Leaving directory '/home/ubuntu/eliza/src'
make: *** [Makefile:251: debug] Error 2

This is an ubuntu 20.04 install and a binary from a previous install works fine... 1.8.2..

**Comment by vanosg** [comment]
Hi, and thanks! Yes, this is a known issue (oops) with 1.9.2. Two things you can do- install the libssl-dev library on your system, which will enable SSL and fix the error, or wait another day or make the code changes shown in https://github.com/eggheads/eggdrop/pull/1272/files  

We hope to merge this into the develop branch this weekend... we just haven't done it yet because \<insert not good reasons here\>.

The 'better' solution overall imho would be to install the openssl libs so that Eggdrop can benefit from the network encryption protection it offers. Good luck!
