### ISSUE TITLE
setlisten can call freeaddrinfo with NULL leading to crash on openbsd

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#1329]
getaddrinfo() can fail and it is unclear from the specification whether the addresslist is set to NULL then or if it still needs to be freed.
On OpenBSD it sets it to NULL and calling freeaddrinfo() with NULL is not allowed.
That code snippet also lacks the gai_strerror() reporting suggestion from the man page of getaddrinfo - it can and does fail.
Our tcl listen command does not support hostnames - maybe it should?

Found by: Release_

**Comment by michaelortmann** [comment]
This Issue should be split:
The more important issue is the `freeaddrinfo(NULL)` and `gai_strerror()`. That will be fixed by #1333.
The second issue, letting listen support hostnames can be done later. And It should be done later, in case we aim to release 1.9.4 soon.
See also:
https://github.com/NetBSD/src/blob/abd1934eaea492770a5b629c883b59771cbf0491/lib/libc/net/getaddrinfo.c#L44
https://github.com/freebsd/freebsd-src/commit/587e285e97a0baf6e0a46c7b5eb04a697320d87d
