### ISSUE TITLE
Documentations (http) for linking bots

### ISSUE THREAD

**Issue by ZarTek-Creole** [eggheads/eggdrop#1396]
Hello, I think the section here [adding-and-linking-bots](https://docs.eggheads.org/using/botnet.html#adding-and-linking-bots) should be updated and factored. It seems to me that during the last year certain functions have been modified and improved or even added to link robots together. I am particularly thinking of the use of certificates in the infra-bots identification process. See [Enable certificate authorization](https://github.com/eggheads/eggdrop/blob/develop/eggdrop.conf#L470)
- I would be interested in a documented procedure to link several bots with their public TLS key to add to the master without a password.
- The part [adding-and-linking-bots](https://docs.eggheads.org/using/botnet.html#adding-and-linking-bots) also does not explain the scenario of connecting robots to an SSL PORT (basic security in 2023 I think)
- A link or explanation on the 'listen port bot' could be added
- in the "Adding and linking bots" part the commands could be in code blocks as in "Making bots share user records"
- and probably other things that I don't think of now

**Comment by ZarTek-Creole** [comment]
> I am particularly thinking of the use of certificates in the infra-bots identification process. See [Enable certificate authorization](https://github.com/eggheads/eggdrop/blob/develop/eggdrop.conf#L470)
> 
Come to think of it: "#set ssl-cert-auth 0" should perhaps be set to 1 by default. Enabling security options by default makes sense to me at a time when the internet is TLS. (for example today, we use https even in development mode, it has become basic to compare to http) in the same vein, currently that eggdrop takes the openssl, we will probably have to review for all connections with TLS. Usually you need a specific reason not to support this.

Reading this reply, maybe it should be in a separate ticket?

**Comment by vanosg** [comment]
Thanks, its a good idea to update the botnet docs with a reference to TLS things. All the TLS settings for botnet were put into the TLS doc, so I added a quick summary and provided a link to the existing documentation that covers this.

Regarding enabling TLS by default, we're not there yet. Eggdrop still doesn't require openssl libs to be installed and enabling this setting by default would prevent Eggdrop from running (and not all users have access to install the dev libraries needed to compile against). We're working towards that slowly; in 1.10 the plan is to require a user to explicitly use the --disable-tls flag if they don't have the libs required to compile TLS support, rather than just silently not compiling against it if they are missing like it does now. A future release will, hopefully, require openssl to be installed and that would be the time to change this setting.
