### ISSUE TITLE
Ability to specify multiple listening IP addresses

### ISSUE THREAD

**Issue by Robby-** [eggheads/eggdrop#151]
Having the ability to specify multiple listening IP addresses would be good to have, so that we do not need to leave `listen-addr` empty, which causes it to listen on every IP address available on the machine which is undesired. A use case for this is to for example have it listen on one IPv4 address and one IPv6 address.

**Comment by Pixelz** [comment]
Current syntax is this:
`listen <port> <type> [options] [flag]`
where `<type>` is one of  `bots, all, users, script, or off`.

Since the type is always known, it should be possible to change the syntax to this:
`listen [ip-or-host] <port> <type> [options] [flag]`

Eggdrop could check the 2nd and 3rd arguments for one of the types and parse the rest of the command accordingly.

**Comment by vanosg** [comment]
Alternately, could we have listen-addr not overwrite itself, and stack them?

listen-addr 1.2.3.4
listen-addr ::whatever::

listens on those IPs?

**Comment by thommey** [comment]
Current proposal:

listen [ip] <port> <type> [args]

IP is optional, port can be identified by being an integer optionally started with + so no ambiguity.
This would allow us to get rid of listen-addr completely.

Config example would be:

listen \* 3333 all
