### ISSUE TITLE
Cosmetic: tcl-commands.doc

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#158]
Couple of problems in the 1.6.22 version of tcl-commands.doc

(1a) There's an extra blank line at lines 21, 108, 1309, 2435, & 2507 .. but NOT at 546, 874, 1098, 1128, 1142, 1161, 1666, 1734, 2411 (these are category headers but the extra lines are inconsistent).

(1b) Extra blank lines at 797 & 1940 [seem weird there; was something removed?]

(2) Incorrect documentation of getudefs

  getudefs <flag/int/str>
    Returns: a list of user defined channel settings of the given type, or
      all of them if no type is given.
    Module: channels

Should be "[flag/int/str/pair]" (optional per [], not required per <>).

(3) setudef / renudef / deludef / getudef don't mention "pair" yet chansettype specifically gives you the "pair" option.

(4) SENDNOTE isn't listed with the rest of the note-related commands (sendnote, erasenotes, et cetera); it's in, potentially, the wrong place.

(5) For the info, at the end, at "match characters," it might relieve some confusion to specifically note: the 3rd & 4th "special characters" (% and ~) only work in bind matches; they do NOT work in commands like STRING MATCH, LSEARCH, or REGEXP. (If they do, I haven't gotten them to work for 18 years).

**Comment by vanosg** [comment]
Thanks! You have a great eye to catch these. 

Re: #3, flag/int/str is the intended functionality
Re: #4, sendnote is part of the core and not the notes module, hence why it is listed where it is. 

I'm adding these changes in now

**Comment by Pixelz** [comment]
Some history on this: `chansettype` (paired with `channel get`) and `getudefs` were added to provide a way for Tcl scripts to know what channel settings are added by Eggdrop (since they change over time) and which has been defined by users. This was primarily intended to make sharing of channel settings across the botnet easier.

`chansettype` is for letting you know what type of setting something actually is, so that you can later set it properly with `channel set`. For some reason, pair was never added as an udef originally. I'm not really sure why. This is related to #65 and might be fixed as part of that.

**Comment by thommey** [comment]
We will probably provide the ability for arbitrary setting definitions where you can validate the value in Tcl yourself (thus also allowing the 'pair/couplet' type) as part of issue #65. The rest should be fixed, closing this.
