### ISSUE TITLE
SEGMENT VIOLATION -- CRASHING by trigger command

### ISSUE THREAD

**Issue by PatriotM** [eggheads/eggdrop#1717]
hi,

i keep getting this error, it doesn't matter which eggdrop version i use, old or new. it's always the same.

as soon as a trigger is executed the eggdrop crashes, the funny thing is, with my old server it worked without problems, even if i copy the eggdrop 1:1 from old to new server it doesn't work. before i had an intel system with little memory now i have an amd system with over 256gb memory. and there it causes problems. i have no idea what i could test anymore
no matter which script I load.

[DEBUG.txt](https://github.com/user-attachments/files/17836541/DEBUG.txt)

[DEBUG2.txt](https://github.com/user-attachments/files/17836565/DEBUG2.txt)

[21:33:43] * Please report problem to https://github.com/eggheads/eggdrop/issues
[21:33:43] * Check doc/BUG-REPORT on how to do so.
[21:33:43] * Last bind (may not be related): ::bc::onEncryptedText
[21:33:42] * Wrote DEBUG
[21:33:42] * SEGMENT VIOLATION -- CRASHING!

**Comment by vanosg** [comment]
Hi, thank you for reporting this issue. Can you share more information about what you're doing- specifically, what does 'a trigger' mean in this case? Is it a script? What type of bind? Is it all binds? Is it on any text that isn't a trigger? What context is happening around the crash event? Anything additional you can provide is helpful.

You mention you moved on your old server- did you recompile eggdrop on the new server, or just copy the entire directory over?

Thanks!

**Comment by michaelortmann** [comment]
Any binaries (executables) could need recompilation from source, because some compiler flags like `-march=native` used during compilation may bind (optimize) a binary to a specific CPU instruction set. That includes all eggdrop modules and libraries (shared objects) that are to be loaded, like `DH1080_tcl.so` which i found in a n (untrusted?) binary blowcrypt package.

**Comment by PatriotM** [comment]
hi, thanks for the feedback, i have now found the problem and i can proudly say that it was not the eggdrop!
i have already got white hair, as i have been at it for a few days, here is the procedure that has caused problems.

`proc cregsub { text } {
	regsub -all {\002|\003([0-9]{1,2}(,[0-9]{1,2})?)?|\017|\026|\037} $text {} text
	set text [mysqlescape $text]
	return $text
}`

i use these to remove colors,bold,underlines from the arguments to avoid further problems. with `set arg [cregsub $arg]`

Since my script is very large, I did not find the problem at first.

on the new system debian 12 is now running mariadb instead of a pure mysql like on the old server. it seems that mariadb is not 100% compatible, maybe someone of you has an idea how i can make this procedure work again, i know that this is a regular pure eggdrop support. but i would still be open and happy for an idea.

**Comment by thommey** [comment]
In general I would move away from mysqltcl to the universal database support in [TDBC](https://wiki.tcl-lang.org/page/TDBC).
Then you can safely make parameterized SQL statements like so:
```tcl
package require tdbc
package require tdbc::mysql

tdbc::mysql::connection create db -host .. -port .. etc.

set text "[stripcodes ...]"; # or your regsub but only for IRC chars, no SQL escaping
db eval {INSERT INTO texts (nick, text) VALUES ($nick, $text)}
```

I realize converting your whole script might be a lot of effort but with safe SQL statements without manual escaping I'd say it's worth it.

In general though I don't think mariadb and mysql are incompatible but the mysqltcl extension might be too outdated to work, because it is based on an ancient C API.
