### ISSUE TITLE
dns.mod not working on NetBSD

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#174]
When Tcl is threaded under NetBSD 6.1.5, dns.mod doesn't load because: _res is not supported for multi-threaded programs. Abort trap.

Found by: fhorst

**Comment by michaelortmann** [comment]
netbsd$ uname -a
NetBSD netbsd 6.1.5 NetBSD 6.1.5 (GENERIC) amd64

netbsd$ ./eggdrop -nt

Eggdrop v1.8.3+acupdates (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
[20:06:27] --- Loading eggdrop v1.8.3+acupdates (Mon Sep  3 2018)
[20:06:27] Listening for telnet connections on 0.0.0.0:2513 (all).
[20:06:27] Module loaded: blowfish        
_res is not supported for multi-threaded programs.
[1]   Abort trap (core dumped) ./eggdrop -nt

gdb:
[...]
#3  0x00007f7ff4c01f7d in init_dns_core () at .././dns.mod/coredns.c:1277
[...]

src/mod/dns.mod/coredns.c: init_dns_core(): line 1277:
_res.options |= RES_RECURSE | RES_DEFNAMES | RES_DNSRCH;

RES_RECURSE, RES_DEFNAMES and RES_DNSRCH are the default, see:
http://netbsd.gw.com/cgi-bin/man-cgi?resolver++NetBSD-current

so, adding NETBSD_HACKS to aclocal.m4 and #ifndef NETBSD_HACKS to src/mod/dns.mod/coredns.c line 1277 would fix this.

**i could fix some code like this in dns.mod to be compatible to netbsd, but that wont be enough, because _res is used in a lot of places and must probably be fixed in all of them. i like netbsd but i stop here now.**

see also:
https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/include/resolv.h

**Comment by michaelortmann** [comment]
Please change the title of this issue to NetBSD, because i tested FreeBSD, OpenBSD, Dragonfly, TrueOS, and i found only NetBSD suffering.

**Comment by Cizzle** [comment]
So do we consider this fixed or only workarounded?

**Comment by michaelortmann** [comment]
Its a workaround, but this Issue can be closed as fixed then, because for the real solution we have #669.
