### ISSUE TITLE
Fix format string warnings.

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#195]
Compile with -Wformat -Werror=format-security, fix it.

**Comment by andy5995** [comment]
I see the warnings:

```
./main.c: In function ‘do_arg’:
./main.c:521:9: error: format not a string literal and no format arguments [-Werror=format-security]
         printf(EGG_USAGE);
         ^
./main.c: In function ‘main’:
./main.c:1079:5: error: format not a string literal and no format arguments [-Werror=format-security]
     printf(MOD_NOCRYPT);
     ^
cc1: some warnings being treated as errors

```

And where they originate from:

```
lang.h
244:#define EGG_USAGE               get_language(0x700)

main.c
521:        printf(EGG_USAGE);
andy@oceanus:~/src/eggdrop/src$ ack-grep -i mod_nocrypt
lang.h
392:#define MOD_NOCRYPT             get_language(0x20d)

main.c
1079:    printf(MOD_NOCRYPT);

```

Is this something that needs to be changed? I'm not familiar with get_language(), but if the devs wanted to give me a few tips, I could make the change.

**Comment by andy5995** [comment]
I was able to figure some things out. Here's a patch. Let me know if changes need to made.

[195_format_string_warning.patch.txt](https://github.com/eggheads/eggdrop/files/440995/195_format_string_warning.patch.txt)

**Comment by vanosg** [comment]
Andy, thanks for submitting this! It's been on the to-do list for quite some time. I'm happy to merge this in, but if you're interested for getting 'credit' on git, do you want to submit this as an actual pull request? If you want/need help on that, you can join #eggdrop on Freenode and we can walk you through it. Otherwise, no worries and I'm happy to review this shortly and incorporate as needed. Thanks again!

**Comment by andy5995** [comment]
You're welcome.

I wasn't sure where the newlines were wanted.
