### ISSUE TITLE
# signs in eggdrop.conf not being ignored

### ISSUE THREAD

**Issue by andy5995** [eggheads/eggdrop#237]
To be honest, I'm not sure if this is an issue, or if I made it an issue.

When I configure Eggdrop, I usually comment out these lines so this section looks like the following:

```
set servers {
    irc.oceanus.localdomain:6667
 #  irc.quakenet.org:6667

#  another.example.com:7000:password
#  [2001:db8:618:5c0:263::]:6669:password
#  ssl.example.net:+6697
}
```

If the first server has a # sign in front of it, and the second server doesn't, Eggdrop will not connect to the second server, instead, it will try to connect to '#' and fail, and then not try to connect to any more in the list.

As I said, not sure if it's really an issue, I figured I'd let the devs make that determination. Where I got fouled up is that I'm so used to lines with # signs in .conf  files being completely ignored, but I understand the logic behind why Eggdrop didn't like what I did, and besides, the original has no # signs. It really depends on if you think other users might do the same thing.

Here's the original, for reference:

```
set servers {
  you.need.to.change.this:6667
  another.example.com:7000:password
  [2001:db8:618:5c0:263::]:6669:password
  ssl.example.net:+6697
}
```

**Comment by Pixelz** [comment]
The Eggdrop config file is for all intents and purposes a Tcl script, being read by the Tcl interpreter. Because of this, it is subject to semantics of the Tcl programming language.

Tcl is made up of a series of commands with arguments. In order for an arguments to have spaces in them, grouping is needed. There are two different kinds of grouping in Tcl. The most obvious one being quotes
`putlog "Hello, world!"`

The second type of grouping is braces. The difference between the two is that no substitutions are performed if braces are used, while substitutions are performed if quotes are used. Another difference with braces is that various characters that have special meaning in Tcl are ignored. This includes whitespace and newline characters.

The following example:

```
set servers {
  you.need.to.change.this:6667
  another.example.com:7000:password
  [2001:db8:618:5c0:263::]:6669:password
  ssl.example.net:+6697
}
```

Could also be written like this:

```
set servers "you.need.to.change.this:6667 another.example.com:7000:password [2001:db8:618:5c0:263::]:6669:password ssl.example.net:+6697"
```

This is how it is interpreted by Tcl after newlines and whitespace are stripped.

In the case of comments, the Tcl manual has the following to say:

>  If a hash character (“#”) appears at a point where Tcl is expecting the first character of the first word of a command, then the hash character and the characters that follow it, up through the next newline, are treated as a comment and ignored. The comment character only has significance when it appears at the beginning of a command. 

This means that you cannot put comments in the middle of a grouping.

I hope this has been helpful to explain why this behavior exists and why there's nothing much we can do about it.

**Comment by andy5995** [comment]
Yes, thank you for the comprehensive explanation. The question remains if there should be a note in the config that # signs within braces can not be used.

**Comment by Pixelz** [comment]
That sounds good to me, seeing as this particular behavior is not obvious.

**Comment by Cizzle** [comment]
> @andy5995 If the first server has a # sign in front of it, and the second server doesn't, Eggdrop will not connect to the second server, instead, it will try to connect to '#' and fail, and then not try to connect to any more in the list.

In my tests, the behaviour is slightly different and corresponding to what @Pixelz has explained: it will round-robin over all the lines, including the # as part of the hostname. So it will first try and fail on the first entry, but then go on to the second entry and successfully connect to that. After another .jump it will try the first one again (other others) etc.

Anyway, it should indeed be added just above the setting that # cannot be used to properly disable a serverline.

**Comment by Cizzle** [comment]
Having done some more tests I partly reproduced @andy5995's behaviour. There is (again completely corresponding to @Pixelz' explanation) a difference between putting the # in front of the server with and without whitespace between. With whitespace inbetween, the # is regarded as a server and eggdrop will try connecting to just '#' and fail. However the next server will be the one that had to be commented out, but I assume @andy5995 just didn't wait long enough for the retry with the next in the list.

Anyway, I encountered this problem while working on a solution that effectively ignored the lines starting with a #, but there is no 100% working one. So I came up with the following choices to "fix" this issue:
- no skipping of any lines and just add in config that no # can be used (the original proposition)
- skipping of servers with # as first char (#server:port) and mention exact method in config
- the above plus skipping of servers with # and whitespace inbetween (whitespace also means newline though) and mention in config # can be used but not with comenttext after or alone on a line (see example)

The third option means that in the following example, server1, server2 and server4 will be skipped:
```
set servers {
#server1
# server2
server3
#
 server4
#commenttext server5
}
```

Please share your thoughts.
