### ISSUE TITLE
flood-size triggers wrong bind type and the default might be confusing

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#242]
So,

cfdf0ec1 introduced flood-size channel flood which triggers based on bytes.
It is common for users to disable flood-chan by setting it to 0:0, but flood-size still triggers.

It triggers the "pub" type in the flud bind, which is confusing, instead of either using a new type, or, if it's so entagled with pub that it is just another trigger for the same type, it should at least not be this confusing that you have to set both to 0:0. Or something. Worth discussing.

Found By: Manuelchen

**Comment by vanosg** [comment]
flood-size triggers based off of text sent to the channel. As I understand this setting, it is designed for 'low and slow' type floods, where a malicious user types long lines of garbage, but at a slow enough pace where time-based flood detection doesn't catch it. Under that definition, I think having it return as a pub is fair, since that's what is actually triggering it- just a different way of using pub. 

This is tough, because all the other flood types are directly linked to a bind. If we were to introduce a new type, it would have to be something that is bind-able; something like SIZE? PUBS? that just triggers if you get X amount of data in a time? I'm not sure what another bind type would look like in terms of triggering bounds or how it would be implemented. Or can we just 'hide' a bind that you cant use with the normal bind command? Drop some code into check_tcl_bind() that allows a PUBS bind to be passed as if it were a PUB?

I agree a pub could be confusing. This feels to me like a smaller use case, is this something that could be fixed with a documentation update that calls attention to the dependency between the two? Maybe move it right next to flood-chan in the documentation?

**Comment by thommey** [comment]
Related to #271

**Comment by vanosg** [comment]
This feature was reverted by 2f316eb9 and will be rewritten to address this. We will track this via #271 to get fixed
