### ISSUE TITLE
Feature request: --with-zinc and --with-zlib

### ISSUE THREAD

**Issue by eelcohn** [eggheads/eggdrop#251]
When compiling Eggdrop it sometimes cannot find zlib.h and/or libz.so which are needed for the compress module. It can be fixed by copying the files, but maybe a configure option would be a nice feature, so the user can explicitly specify the location of both files?

PS the other issues I've entered were cross-compiling related. This is a 'regular' issue :)

**Comment by vanosg** [comment]
this sounds like a valid request to me. Anyone else?

**Comment by thommey** [comment]
This only stays relevant for compiling compress.mod and using Tcl <= 8.5, because Tcl >= 8.6 requires zlib itself and gives us the tools to link to it. I don't think it is still necessary, given that compress.mod is not essential and people who need it can manually specify LDFLAGS/CFLAGS to add -L/-I paths, or just use Tcl8.6.

**Comment by vanosg** [comment]
I can buy that. Suggest we make a wiki post discussing the solution for easy reference.
