### ISSUE TITLE
Add proper oident support

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#259]
by writing localip:localport -> remoteip:remoteport { reply "foo" } into the config, not overwriting the whole thing with a global {} directive

**Comment by michaelortmann** [comment]
Can you please explain in more detail? I know what an identd is and a guess when you say oident you mean the identd implementation named oidentd. Still i have no idea, what you mean. Does it have to do with eggdrop identing users, as it tries for telnet connections to the bot, or does it have to do with eggdrop using an oidentd for identing herself against an asking ircd / external source? What is the problem here? Is it even still relevant?

2nd try to understand. you run oidentd at the same host that eggdrop is running. and you want eggdrop to be able to write into oidentds (local user) config file (something like $HOME/.oidentd.conf) so that any external request to your oidentd/eggdrop is properly answered? if so, i wonder, why this was not already implemented ages ago. maybe because there are workarounds in form of tcl out there like https://tclarchive.org/download.php?id=1780 or ppl just add a fixed line for theyr bot with an editor of their choice into that config. what if the user changes the username in the bot config file... can he expect eggdrop will update the ident config? can it do so in a sane way?

**Comment by Cizzle** [comment]
Yes thommey, either close this or be more clear (and then implement it!).

**Comment by michaelortmann** [comment]
Discussion on IRC with thommey resulted in that we will overwrite the whole file, due to anyone else doing it also.
