### ISSUE TITLE
Feature request: logging of the bot's public output to a channel

### ISSUE THREAD

**Issue by eelcohn** [eggheads/eggdrop#298]
I'd like a feature which outputs the bot's public text to a channel. For example: if I have a quote-script loaded, I can do:
```
.quote
```
And Eggdrop responds with:
```
[lamer] This is a quote
```
My command (.quote) gets logged by the 'p' option, but the response from Eggdrop not. I'd like to see an option for example 'q' which logs the bot's output.

**Comment by thommey** [comment]
Hi,

this is difficult to 100% reliably do, because the IRC protocol does not provide any feedback. The bot could, for example, be in a moderated channel and not able to talk (the feedback for that exists but it near impossible to associate with the message you tried to send - queuing, delays, etc.).
However, since Eggdrop 1.6.20 you can intercept Eggdrop's output to the server with a script, and I wrote a script to log Eggdrop itself with that to loglevel 'p' as well as normal users (that is also compatible with lower versions).

You can download it [here](http://thommey.tclhelp.net/dl/dl.htcl?id=5).
Let me know if that solves your problem adequately.

**Comment by thommey** [comment]
After discussion, we think it might be a useful feature to have in the Eggdrop core without an additional script, as a config setting, I'll leave this ticket open as a reminder of that.

**Comment by vanosg** [comment]
Updating this; enabling the ircv3 capability "echo-message" (https://ircv3.net/specs/extensions/echo-message) is probably the right answer to meet this need. Assuming the server supports it, it can be added to the enable list in the Eggdrop config file in the CAP section. I'm going to close this issue, but if there are opposing opinions we can re-open it... i figure 6 years without any work is probably an indicator of lack of interest.
