### ISSUE TITLE
bind invite gets the hostmask on every other triggering

### ISSUE THREAD

**Issue by jack3-again** [eggheads/eggdrop#354]
Full explanation already written out here:   http://forum.egghelp.org/viewtopic.php?p=105906#105906
See the short little demo script there.

**Comment by Pixelz** [comment]
Seems like the proc doesn't get called with full args every other time. I wrote this small test script:
```
bind raw - invite test
proc test args {
    putquick "PRIVMSG #foo :raw invite triggered: [join $args ", "]" 
}
```

This is the output:
```
<me> INVITE Rimmer #bar
<Bot> raw invite triggered: Pixelz!pix@my.hostname, INVITE, Rimmer #bar
<me> INVITE Rimmer #bar
<Bot> raw invite triggered: Pixelz
```
And it repeats like that

**Comment by michaelortmann** [comment]
sometimes the raw bind is executed before the builtin ignore. sometimes the other way around.
the builtin ignore modifies the args in chan.c gotinvite() in the following 2 lines:
newsplit(&msg);
nick = splitnick(&from);
i prepare a fix to copy msg and from before those function calls.
but i have 2 questions now:
should we enforce a special sequence of raw binds and builtins? and why is it random anyway?
dont other builtin functions behave the same, when also raw binded?

**Comment by michaelortmann** [comment]
sometimes the raw bind is executed before the builtin invite. sometimes the other way around.
the builtin invite modifies the args in chan.c gotinvite() in the following 2 lines:
newsplit(&msg);
nick = splitnick(&from);
now i can confirm its the same as issue #387, but its not only newsplit() but also splitnick() and any other function modifying the parameters of the builtin functions. btw: we are able to reproduce the problem now again. we must only do the example of pixelz. in my case the sequence toggles every time i do the /msg invite ...
first i prepared a fix to copy "msg" and "from" before those function calls.
but there are more builtins like this.
then it turned out its better to fix the order of binds.
the toggle was found. it is probably an optimization, moving last recently used binds to the front of the bind table.
this leads to toggling the order of execution every time the same binds are triggered.
now pushed a new solution which keeps the builtin functions as is, keeps the optimization as well, but fixes it, so that the optimization is only done, when there is only exactly 1 bind for the trigger.
