### ISSUE TITLE
Add SASL support

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#395]
Use libsasl, or write from scratch?

**Comment by Robby-** [comment]
Personally, I'd like something so small like this not to depend on an extra library.

**Comment by vanosg** [comment]
What if it were optional, like we do with openssl via ifdefs, and that functionality is only available if the library is discovered? There's something to be said for allowing others to maintain that portion of code for us, I can see us lagging behind impelementing any updates

**Comment by Robby-** [comment]
I guess that is ok. If possible, please provide `--enable-sasl` or `--disable-sasl` options for `./configure`.

I currently use a TCL implementation for SASL auth, it would be nice if this can keep working and not conflict with the upcoming builtin SASL functionality of eggdrop should I prefer to keep using this instead of the builtin functionality.

Also, I don't know how much flexibility using a library for this offers someone looking to implement SASL in their IRC client, but you should also keep in mind that if services are unavailable, for example due to a netsplit or maintenance, and you connect during such a time, the connection will appear to be hanging until you either stop the SASL authentication attempt (so that you can continue connecting to the IRC network) or until the server times you out if you do nothing, which the latter will be causing you to never be able to fully connect. So, a client-side timeout detection is necessary to avoid this problem. A timeout of only a few seconds, maybe like 5 or something, should be enough. Maybe even make this configurable (e.g. `set sasl-timeout 5`).

**Comment by vanosg** [comment]
If we went that path (and I'm not sure we are), I would absolutely advocate for --enable/--disable flags, just like we do with ssl. Good feedback on that and everything else, thanks!

**Comment by Pixelz** [comment]
It should perhaps be noted that Eggdrop already supports SASL via the "External" mechanism, i.e. using a client certificate. This is supported by for instance freenode as a way to identify with services.

**Comment by Robby-** [comment]
@Pixelz Actually, that is not how SASL EXTERNAL works, you have to really negotiate SASL during connection, which eggdrop does not currently support, so no, it does not support it at all.

What you are describing is in reality an alternative implementation of using certificate fingerprints for services authentication that some services projects have chosen to implement. Depending on the network and services software in use, services may see the client certificate fingerprint and use it to identify you automatically. But this is not guaranteed to work on every network. For example, for networks using Anope this can work, because Anope supports that scenario, and apparently so does freenode (which is using atheme). Then again, on other networks, for services to actually use your certificate fingerprint to identify you, you *have* to negotiate SASL and the EXTERNAL mechanism during connection.

It should also be noted that this alternative implementation method occurs *after* connection has completed, which causes NickServ to still send you the usual notice that the nickname is registered and that you have to identify for it, but then immediately right after that says that you are now identified. It is a side-effect of this alternative implementation that both services have due to how this works.

**Comment by Pixelz** [comment]
I assume that this "alternative implementation" is referred to as "CertFP". A quick search for that seems to indicate that a vast number of networks support identification using that method.

Is there a network that supports authenticating with SASL that doesn't support identifying with client certificate fingerprints?

**Comment by vanosg** [comment]
FWIW, agree with Robby's explanation. And while I'm not an expert, if a server supports SASL, it supports the EXTERNAL method as you described above, which allows external protocols not specifically specified by the SASL specification. Therefor, if the server in question supports SSL/TLS connections, then it should (again, not an expert) support certificate-based authentication via SASL since the server has that functionality.
