### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rcschaff82** [eggheads/eggdrop#442]
Somehow work this into the source command by default.

```
proc sload { file } {
if {[catch {source scripts/$file} err]} {
        putlog "Error while loading $file : $err"
} else {
        putlog "$file loaded without errors"
}
sload file.tcl

```Currently I have this in my eggdrop.conf to catch errors, but it would be nice to just use 
source scripts/script.tcl again.  And Error Should NOT crash the bot.

**Comment by vanosg** [comment]
Hi rcschaff82,

  That is a great idea, but the source command is actually a native Tcl command, not something specific to eggdrop, so we have no control over that. We do have a similar trick documented to what you provided at http://eggwiki.org/Scripterrors , which hopefully people can find, and looks to perhaps be where you found that code in the first place!

**Comment by rcschaff82** [comment]
You could make a built in function, and change the command to "script scripts/thescript.tcl"

A lot of people don't even look, so it really should be made PEBKAC proof.

**Comment by rcschaff82** [comment]
Now I understand why you don't "Catch" the sources.  It seems that if you do, then tcl doesn't initialize the variables.  So maybe this isn't an option...

**Comment by thommey** [comment]
That problem only exists if you use what you proposed and don't uplevel the source. Because then it executes in that proc's context and initializes the variables as proc-local ones instead of global ones.
```tcl
proc sload { file } {
set cmd [list uplevel [list source scripts/$file]]
if {[catch $cmd err]} {
        putlog "Error while loading $file : $err"
} else {
        putlog "$file loaded without errors"
}
```
should do the trick.
But as @vanosg said, the [source] command is a native Tcl command, and we can't just replace it. We could ignore Errors from the config loading (which is also source'd) and simply start eggdrop regardless, but we can't intercept or overwrite the source command itself. I mean, we could, technically, but it would add a layer on top of native Tcl itself, which is not desirable.
We could provide our own proc to load scripts that does it, and recommend using that instead of [source], which might also allow us to store more context information with binds or timers so we can print resource usage per script or something like that, but that's far off in the future if it is even realistically possible.
I'll leave this open and think about providing our own alternative to the source command that does error catching, because of the potential future benefits.

**Comment by rcschaff82** [comment]
That worked like a charm.  I really need to study more on tcl lol

**Comment by rcschaff82** [comment]
For now I used the following in my eggdrop.conf

proc sload { file } {
set cmd [list uplevel [list source $file]]
if {[catch $cmd err]} {
        putlog "Error while loading $file : $err"
} else {
        putlog "$file loaded without errors"
}
}

and replaced all of the source with sload

so 
sload scripts/alltools.tcl
