### ISSUE TITLE
SSL fingerprinting not persistent

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#462]
Found by: Krekas

Link two bots, log in using s_client with a cert, and use .fprint+ to add it in. You can now log in using the cert, without a password. 

However, kill and restart the leaf bot, even though FPRINT is still in the user file, logging in requires a password again. Using fprint + will eliminate this, until the next bot restart.

**Comment by michaelortmann** [comment]
I think i accidentally fixed this issue with #678.

Can someone confirm?

**Comment by michaelortmann** [comment]
**To clarify and reproduce:**

1. Set `ssl-cert-auth=1` in eggdrop.conf
2. Link 2 share bots togather
3. Login to hub via openssl s_client, see doc/TLS
4. Do `.fprint +`

**Then you will find the following:**

1. Login to the hub without password is possible now, as expected.
2. The FPRINT is shared to the leaf, as expected.
3. So login to the leaf without password is also possible now, as expected
3. The FPRINT is written to the userfile at both bots, as expected.

**The bug is:**

All FPRINTFs at the leaf are lost, whenever a userfile is transmitted, due to the share file doesn't contain FPRINTFs.

BTW: This issue was reported 1 year ago, so to say with Pixelz words: Let nobody say that Eggheads is forgetting any bug report.

**Comment by Cizzle** [comment]
To clarify the original issue some more:
 1. fprint added to leaf is saved in userfile and shared with hub
 2. leaf is killed, fprint still present in userfile
 3. leaf is started again, userfile gets overwriten by hub's but fprint is not part of the transfered userfile
