### ISSUE TITLE
ISBAN: overlapping functions

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#531]
Documentation says:

isban <ban> [channel]

  Returns: 1 if the specified ban is in the global ban list; 0
  otherwise. If a channel is specified, that channel's ban list is
  checked as well.

Question: how can you tell if a ban was added BOTH globally and channel-specific?

Coding a check for { [isban * #] && ![isban *] } doesn't work because, while it will isolate bans that are NOT global, it will also hide those that are BOTH global and local.

This is important if a bot master is trying to clean up the ban list, they can't "SEE" why a ban may be re-triggering (especially is STICKY) if it can't be seen / listed.

Solution: ISBAN should either show global (if no chan is listed), or local [channel]-only bans (if a channel is specified). This current "overlap" of returning globally-matching bans when a channel is specified is causing hell!

**Comment by ghost** [comment]
Let's assume that ISEXEMPT and ISINVITE are similarly afflicted.

**Comment by vanosg** [comment]
Hi maimizuno,

  The question you asked was
```
Question: how can you tell if a ban was added BOTH globally and channel-specific?
```
I am interpreting this question to mean these bans were added twice; once via .+ban *!foo@test.com  and a second time as .+ban *!foo@test.com #eggdrop 

To do this, 
```
if {[isban *!foo@test.com #eggdrop] && [isban *!foo@test.com]}
```
will return true if a ban was added both globally and channel specific. Is there some other scenario or setup you have where this is not true? I'm not sure what the overlap you are referencing is. Thanks!

**Comment by vanosg** [comment]
I played with this a little more- what I found (and I assume what you were trying to explain) is that if a only global ban is set, running [isban *!*@hostmask.com #channel] will still return 1, even if a channel ban is not set, only the global ban. 

If that is not what you found, please let me know. But I'll patch the issue I described above shortly... hopefully its the same!

**Comment by maimizuno** [comment]
> [vanosg] I played with this a little more- what I found (and I assume what you were trying to explain) is that if a only global ban is set, running [isban !@hostmask.com #channel] will still return 1, even if a channel ban is not set, only the global ban.

Correct.

"ISBAN <ban>" should only report a global ban match
"ISBAN <ban> <channel>" should ONLY report local (channel) bans. Instead, it will match a global ban as well; there's no way to know WHICH it's telling you about: a global ban or a local ban.

Scenario I was trying to resolve: if a ban is placed by a channel, then an admin decides to "apply a global ban" to "enforce" it (...), ISBAN's reply will be confusing to interpret if building a ban list. The only way to reconcile this is to manually scan both the global and local BANLISTs via LSEARCH -GLOB -INDEX 0 and decide: if  global && !local, presume global.

**Comment by maimizuno** [comment]
[](url)

**Comment by maimizuno** [comment]
![bans](https://user-images.githubusercontent.com/8587591/43363398-b1507594-92b8-11e8-86f7-65aa7d40cea1.png)

**Comment by maimizuno** [comment]
If this behavior is intentional, maybe a companion command would help: BANTYPE \<mask> \<chan>, bit 0 (value 1) = server level ban, bit 1 = channel, bit 2 = global, and any combination would mean it's in multiple places. 

This would ALSO help with testing if the ircd is full of bans (server limit of +b), so you knowto remove some if the value is 2 (channel ban in mrmory, but not on the server currently).

**Comment by michaelortmann** [comment]
the function specification reads "as well" not "instead":

isban [channel]

Returns: 1 if the specified ban is in the global ban list; 0
otherwise. If a channel is specified, that channel's ban list is
checked as well.

Module: channels

not returning 1 if a ban is in the global ban list would break this specification. existing tcls may rely on it. instead of api change i propose to change the function in a backward compatible way. something like:

isban [channel] [flag]

if flag not set: old behaviour

if flag set: new behaviour

or find another/ a better solution for the problem this issue is based on.

(this comment was moved from https://github.com/eggheads/eggdrop/pull/533)

**Comment by maimizuno** [comment]
@michaelortmann My 2¢ (since I brought this whole thing up in the first place): the 'specification' (and the implementation, which obeyed the docs) is, itself, flawed. There shouldn't be such an overlap, because it causes ambiguity. I'm all for avoiding ambiguity and more importantly, I \*embrace\* backwards-compatibility (see all of my other bug reports).

The problem lies in: this issue is a case of "broken since day #1" and, therefore, it should be fixed. Scripts that rely on doc'd functionality are relying on logic-flawed information (the 'mis-function' in question) and, thusly, had to use a skewed logic to get around the problem in the first place (mainly manually scanning the BANLIST on both global and local levels) to resolve the ambiguity. In other words, how do you de-ambiguate which "as well" you're dealing with?

I also suggested a 'check the ban' option above (BANMODE, see previous comment above), but the simpler solution seems to be: fix the real issue and don't cruft-up the core code with "compensatory" commands.

 I'm no fan of breaking things; this was broken from day #1. Gotta draw the line somewhere.

Okay, that more like $2.37, but ... oh well ....

**Comment by maimizuno** [comment]
@vanosg Can you verify if ISEXEMPT & ISINVITE are similarly affected?

**Comment by ghost** [comment]
Acknowledged by coders; issue no longer needed.

**Comment by ghost** [comment]
Changed the title; don't know why I typed "ISOP" when it's \*CLEARLY\* not that.
