### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#535]
I'm told that this has been discussed before, but I'm not going to search through over 500 entries to find it, so let's start fresh. Thanks to Pixelz for some of the background information.

According to everything I've read, the following are true:

(1) Eggdrop, if SSL is compiled in, can do SSL connections for botnet (if you listen +port)

(2) Eggdrop, if SSL is compiled in, will attempt to do STARTTLS if the bots, on both ends, are SSL-enabled but a non-SSL port is being used for the connection attempt

(3) Eggdrop, if SSL is compiled in, will *NOT* link bots if no certificate is available when STARTTLS is thrown (as per the config settings)

There is a specific problem as a result: for those on "admin [group-policy] limited windows systems" with WinDrop (which is based on Eggdrop, thus this being reported here, before anyone yells at me -- I'll yell right back), the use of OPENSSL may not be available to a given user in a multi-user environment (or a simple, single-user computer due to whatever) where certificate generation isn't wanted, desired, or possible. Between group policies and administrative lock-outs in various configurations make this a real issue.

Currently, I have to put up an off-line (NO-IRC, remember those?) hub bot just to hub a local cluster of automatically-SSL-compiled-in bots because I can't link them together through LOCALHOST. I don't have the option of getting the "non-SSL" port of WinDrop because the botnet they hook into *requires* SSL connections there (I can't make those consistently connect / hold). In addition there are several 1.6.13, 1.6.19, and 1.6.21 bots in there that can't handle the SSL connections anyway. Duct tape, spit, bailing wire, and magic is holding that part of the botnet together.

Now, why shouldn't I have the right (and control) to link my own LOCALHOST bots without being ***FORCED*** to set up certificates for each one??? Shouldn't I have the right to make that decision for myself?

I've been told that there was a suggestion "floating around" (not found in these 500+ issues) of using a port # of "-3333" where "-" says: DO-NOT-USE-SSL/STARTTLS-NO-MATTER-WHAT (in other words, "stay in plaintext"). It seems that, that suggestion either died or just wasn't supported. In either case: why?

Shouldn't we, as bot owners *of any kind and of any version and of any OS (given the various restrictions possible)* have control of that?

Revive the "-port" discussion.

**Comment by skralg** [comment]
I personally feel like we shouldn't STARTTLS if a +port isn't specified.  I have the same problem linking bots and sharing userfiles when the all run on the same interface, and in the same shell.  Compiling without SSL fixes this, but prevents SSL IRCD links at the same time.

**Comment by vanosg** [comment]
```(1) Eggdrop, if SSL is compiled in, can do SSL connections for botnet (if you listen +port)```
If SSL is compiled in, Eggdrop defaults to all botnet connections as SSL. If a leaf bot w/o SSL connects to a hub bot with SSL, the hub bot will fall back to non-SSL. If an SSL leaf bot connects to a non SSL hub bot, the connection also will fall back to a non-SSL connection.

```(2) Eggdrop, if SSL is compiled in, will attempt to do STARTTLS if the bots, on both ends, are SSL-enabled but a non-SSL port is being used for the connection attempt```
Not sure I understand this fully, but even if a non-+ port is specified (ie, 3333 instead of +3333, and both bots have SSL, the link will be SSL. 

```
(3) Eggdrop, if SSL is compiled in, will *NOT* link bots if no certificate is available when STARTTLS is thrown (as per the config settings)
```

Correct, because the SSL depends on a cert/key pair. Without both specified, the link does cannot occur. 

So to recap, by default, a non-SSL eggdrop (ie, a 1.6.x bot) can link with a 1.8.x bot. If SSL is not available on the leaf 1.6, the 1.8 hub will allow a non SSL connection, all by default. There should be no instability or other weirdness in that situation, it is the same botnet connection that exists in the 1.6 line. 

I'll also point out the 'make ssl' option that creates a certificate usable by eggdrop. Certs aren't required to be used by eggdrop 'just because', they're only required if an SSL connection is being made, and errors as such. The certs created are named the defaults in the config file. These two settings are commented out by default in the config, and the bot will not use SSL unless these settings are uncommented. 

This comment isn't an opinion on your issue; just a list of facts/features you may or may not be able to do to workaround your current issues, based on how we built the code.

**Comment by maimizuno** [comment]
> I'll also point out the 'make ssl' option that creates a certificate usable by eggdrop. Certs aren't required to be used by eggdrop 'just because', they're only required if an SSL connection is being made, and errors as such. The certs created are named the defaults in the config file. These two settings are commented out by default in the config, and the bot will not use SSL unless these settings are uncommented.

[REDACTED]

The problem is: since connecting 1.8 to 1.8 (if SSL compiled) is automatically done as an SSL connection, you \*MUST\* create and use the cert/key pair. Otherwise, by the terms quoted above (which you confirmed), the connection will fail.

That doesn't help us, your customers.

I do \*NOT\* support the idea of: "You MUST use SSL if you're going use our product, regardless of your situation (despite the fact that there are all kinds of shells, configurations, and non-*nix machines running your product).! F U otherwise!" This is the current setup, and, as noted by @skralg above, there are users (besides me) who are having problems with this demand!

[REDACTED]

Despite how easy you make it all sound (well, hell, you wrote it, so, of course you're going to tell us "it's easy!"), we, the users, seem to have a problem with it. We want the option!

I just \*\*WASTED\*\* THREE HOURS trying to work-around this disaster. If you knew my personal circumstances, you would understand why I am so angry, I actually deleted the fucking eggdrop directory, took a breath, then restored from a backup later and tried again.

I am not happy. And I don't think your customers like the "we're smarter than you so we'll decide how / when / why you must use SSL" ideal coded into 1.8. We got enough of that from Microsoft all these years.

[REDACTED]

This is one very clear reason users might downgrade to 1.6.21 and stay there. I know I will have to.

[REDACTED]

> This comment isn't an opinion on your issue; just a list of facts/features you may or may not be able to do to workaround your current issues, based on how we built the code.

Understood.

I did find a work-around, but it's not generic; otherwise, I'd post the details.

... three hours later.

[REDACTED]

So, how hard is it to either (1) enable the "-port" method, or, (2) config variable: $::no-ssl-connections ? Are we really just S-O-L? This configuration intentionally denies your "can't-always-use-SSL" users the use of your product. Is that the intention?

**Comment by vanosg** [comment]
I'll shorten the answer even further, in case it was lost- 
```I don't have the option of getting the "non-SSL" port of WinDrop because the botnet they hook into *requires* SSL connections there ```

**Eggdrop does not require the use of SSL to link a bot in**. Your comments seem to indicate you think it does? If SSL is not available on a bot, that link automatically rolls back to plaintext. No bot will reject a non-SSL connection to it unless the port is explicitly prefixed with +.  In your example above, there should be no reason a Windrop cannot link with a 1.8 bot. 

If you are having issues, it is not because the current version of Eggdrop is rejecting or otherwise unable to link non-SSL bots, because a 1.8 bot can link with a 1.6 bot with no workarounds needed.

**Comment by ghost** [comment]
Completely missing the point. Forget it. It is as I feared.

**Comment by Cizzle** [comment]
Implementing `-<port>` after vivid discussion.

**Comment by ghost** [comment]
I would \*LOVE\* to see a log of this discussion, to understand why: when I said it, it was dismissed but others discuss it, you do it. (Not the first time, cf. HALFOP, ENCRYPT, and others.) I need to know what language to speak in order to be listened to.

**Comment by skralg** [comment]
We did not dismiss this.  You are not the only one with this problem.  This has been discussed many, many times since 1.8 was released.  You helped to make it more of a priority.

**Comment by thommey** [comment]
I have been the only one trying to preserve the original state of enforcing SSL between 1.8 bots (if compiled in, which is default and automatic). I gave up on that stance months ago, as we have been unable to weed out some sharing-related bugs with it for a long time now. They are difficult to reproduce and debug, so allowing "-port" and 1.8 bots to link without ssl is a workaround for now. Nobody went forward to implement it or announce it in the meantime though. This brought it up again. and I am glad we now have a reminder to do it in our roadmap (here).
