### ISSUE TITLE
PASSWDOK doesn't obey docs

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#560]
The docs say: you can test if a user has a blank password (or had their password blanked) if you test against "" (empty string), or "-" 

... which is a lie.

\<Domino> ## adduser DELETEME
\<Samantha> [TCL (0ms)] 1
\<Domino> ## passwdok DELETEME  ""
\<Samantha> [TCL (0ms)] 0
\<Domino> 04## passwdok DELETEME -
\<Samantha> [TCL (0ms)] 1
--> Inconsistent

Before you ask: "does it do anything different if you set-then-clear the user's password?" ... it does not.

\<Domino> ##  setuser DELETEME PASS [encrypt [rand 999999999] [rand 999999999]]
\<&Samantha> [TCL (0ms)] 
\<Domino> ##  passwdok DELETEME  ""
\<&Samantha> [TCL (0ms)] 0
\<Domino> ##  passwdok DELETEME  -
\<&Samantha> [TCL (0ms)] 0
--> Correct responses.

\<Domino> ##  setuser DELETEME PASS
\<&Samantha> [TCL (0ms)] 
\<Domino> ##  passwdok DELETEME  ""
\<&Samantha> [TCL (0ms)] 0
\<Domino> ##  passwdok DELETEME  -
\<&Samantha> [TCL (0ms)] 1
--> Inconsistent again

Either the 1.8.1+RC1 encryption debacle broke this (...), the command has always been broken, or the docs have always been wrong.

Either way ....

**Comment by michaelortmann** [comment]
the following commit broke it: https://github.com/eggheads/eggdrop/commit/d584c2f6a711b4b3a9e26df0d0ce2d569b589156#diff-86958dec14df0fbca0b596014ea8901a
looks intentionally.
so i would say the docs are wrong now.
btw, in line:
  if (!cmp || !pass || !pass[0] || (pass[0] == '-'))
the !pass makes no sense, because if pass were a nullpointer, the function would break some lines before, when accessing pass[0]
it doesn't seem to be a good idea to let 1 function handle 2 cases here. especially when it seems to be a security related one.
i propose to code a seperate "check if a password is set" function for eggdrop 1.9 and make this function here return 1 only if password matches.

**Comment by ghost** [comment]
From dcc.c:

  /* No password set? */
  if (!glob_bot(fr) && u_pass_match(dcc[idx].user, "-")) {

The code doesn't seem to honor "" anyway.

**Comment by maimizuno** [comment]
@michaelortmann I see what you mean....

**Comment by maimizuno** [comment]
@michaelortmann How can I find you on IRC?

**Comment by michaelortmann** [comment]
*sleepy* bai bai for today...

**Comment by michaelortmann** [comment]
@ghost: that code doens't need to. its only a user of the passwd match function, and it uses '-' to do so. sane and valid.
