### ISSUE TITLE
Version numbering: proposal

### ISSUE THREAD

**Issue by ghost** [eggheads/eggdrop#572]
There have been multiple issues with version numbers.

Example, a version I got from geteggdrop.com has a numver of 1080303, which confused the hell out of everyone, as a just-released-patch (1/2 hour ago) updated the version from 1080301 to 1080302.

I propose a solution (which will break scripts):

#define EGG_STRINGVER "1.8.3"
#define EGG_NUMVER 10803[01]01
#define EGG_PATCH "whatever"

The purpose is: 1 \<major> \<minor> \<single digit: 0 = RC, 1 = official release> \<patch or RC level>

So, 10803001 is an RC (RC1 usually), and 10803101 = official release. And, RC versions vs official release versions will sort lexicographically.

Ambiguity destroyed.

**Comment by Robby-** [comment]
The whole version numbering thing in the eggdrop project needs to be rethought and be consistently applied by everyone involved. For example: when you release a stable version: immediately bump the git version instead of leaving it and only bumping again after another stable release. Incorporating a partial commit hash would also be very nice to have as currently there is no way to determine which revision you are on from within eggdrop, unless you check it with git.

**Comment by ghost** [comment]
@michaelortmann suggested: will any APIs be broken if the format is changed (either by my suggestion or any other format)?

**Comment by michaelortmann** [comment]
1. why not put a timestamp into free text field EGG_PATCH for every commit. could be automated with some git hook i guess. because when we cant put a hash into it, which we cant, a timestamp would be very quick to look up later without knowing hashes or names...

example: #define EGG_PATCH "20180823052400"

2. why not analyze other projects and copy an existing/working version strategy instead of developing our own one?

**Comment by ghost** [comment]
I've always thought timestamps are unambiguous enough to be good enough. No duplication, no parallelisms (RC 01 vs full release 01).
