### ISSUE TITLE
botattr | There are no bot flags BOTNET on #eggdrop

### ISSUE THREAD

**Issue by cinwie** [eggheads/eggdrop#614]
.botattr BOTNET |s #eggdrop
[09:47:25] #-HQ# (#eggdrop) botattr BOTNET |s
There are no bot flags for BOTNET on #eggdrop

iam use eggdrop 1.8.3

**Comment by vanosg** [comment]
Hi @cinwie . This is currently tracked in #525 and has a PR submitted to fix in #569 . I'm going to close this issue here so we only have one issue tracking it, but it should be merged within the next day or so into our develop branch. Once it is, we'd love to get any more feedback from you to ensure it is working properly. Thank you very much for taking the time to report this important bug!
