### ISSUE TITLE
evaluate if the userfile could be converted to be a tcl script

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#62]
| Trac | Data |
| --: | :-- |
| Ticket | 62 |
| Reported by | @thommey |
| Status | new |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.0 |
| Version | 1.8.0 CVS |

the configfile is a tcl script, the chanfile is a tcl script, why not the userfile? maybe it could be done with introducing a function to set an already encrypted password. it'd be better to have all those being a tcl script I think ... this is just a discussion proposal

**Comment by thommey** [comment]
**Comment by pseudo**
I believe this would be a very bad idea. It would introduce compatibility issues with userfile sharing - 1.8 won't be able to share with older versions!

I'm personally against this.

**Comment by ghost** [comment]
At some point, things have to be broken to advance (like pre-1.3 scripts and 1.3 bot scripts). It makes sense to have all aspects as TCL scripts, instead of select things. Compression should take care of any additional overhead, unless you tokenize the items (\x80_!mymask@my.domain \x80_!myothermask@my.domain \x81 ENC'DPASS \x82 nmtjxo \x83 nmo #channel1 \x83 mo #channel2 and so on)

**Comment by ghost** [comment]
There are already scripts to do this (I wrote one of my own because the ones out there sucked). So, it's really only a matter of parsing, IMnshO.

As far as userfile sharing goes, is the bot actually READING the userfile to send data (which would create a compatibility issue), or sending information from memory (which is \*NOT\* a compatibility issue)? If not, then it's all a matter of re-writing the parser to read / write a TCL script userfile.

Two questions arise from this, both having to do with formatting:

(1) a pre-formatted TCL list containing specific data indeces; unset elements = ""
Example:
# This is the new userlist format, version 1
# $ID blah blah blah
adduser Domino {857246400 +jU/ofy7.HIn nmtxolvf {#StormBot mpjkcoblxswvhg12345678 - 1 0 0} {{#stormbot nmolvf 1531531531} {#bothouse nmolvf 1531531531}} {Ami-*!Mercury@ShabonSpray.ShineAquaIllision.Org Ami-*!Me-Too@AGDE0783.ipt.aol.com} {} {{otherdata value} {otheruserinfo value ..} {fstat {0 0 0 0}}} {{xtra1 value} {xtra2 value ...}}}
( this considers moving "created" into the main user info stream, per #361 )

(2) tagged elements, which allow for "skipped" items and makes order irrelevant
Example:
# This is the new userlist format, version 2
# $ID blah blah blah
adduser Domino {created 857246400} {chattr nmtxolvf} { pass jU/ofy7.HIn} {console {#StormBot mpjkcoblxswvhg12345678 - 1 0 0}} {chattr nmolvf #stormbot 1531531531} ...
where chattr \<flags> \<channel> \<lastseen>

And, no, that's not my real password hash.

(3) ... or a third option: XML? (No no oh cod no save the children and don't use XML!). That would require XML parsing become part of core, not relying on tcllib.

**Comment by vanosg** [comment]
No intention to implement this at this time
