### ISSUE TITLE
Static code analysis report by cppcheck

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#69]
| Trac | Data |
| --: | :-- |
| Ticket | 69 |
| Reported by | vBm |
| Status | new |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.0 |
| Keywords | cppcheck |
| Version | 1.8.0 CVS |

I've downloaded CVS nightly snapshot from [ftp](http://www.eggheads.org/redirect.php?url=ftp://ftp.eggheads.org/pub/eggdrop/source/snapshot/eggdrop1.8-snapshot.tar.gz) and was scanning _src_ dir using cppcheck gui built from latest [git head](https://github.com/danmar/cppcheck/commit/1bc8a2b6ba14068f545cdcee9f63ec1df1d1e9c7).

This is what cppcheck found.

Note: There might be some false positives but none the less i still think not 100% is false positive. 

 [botmsg.c:891]: (style) Variable 'work' is not assigned a value
 [botcmd.c:330]: (error) Undefined behaviour: s is used wrong in call to sprintf or snprintf. Quote: If copying takes place between objects that overlap as a result of a call to sprintf() or snprintf(), the results are undefined.
 [dns.c:467]: (style) Variable 'r' is assigned a value that is never used
 [dns.c:472]: (style) Found obsolete function 'gethostbyaddr'. It is recommended that new applications use the 'getaddrinfo' function
 [dns.c:482]: (style) Found obsolete function 'gethostbyaddr'. It is recommended that new applications use the 'getaddrinfo' function
 [mem.c:373]: (warning) Redundant assignment of "i" to itself
 [mem.c:403]: (warning) Redundant assignment of "i" to itself
 [mem.c:382]: (error) Memory leak: x
 [misc_file.c:55]: (error) Resource leak: fi
 [net.c:200]: (style) Found obsolete function 'gethostbyname'. It is recommended that new applications use the 'getnameinfo' function
 [userrec.c:84] -> [chan.h:116]: (style) Struct 'maskrec' hides typedef with same name
 [compat\gethostbyname2.c:31]: (style) Found obsolete function 'gethostbyname'. It is recommended that new applications use the 'getnameinfo' function
 [compat\gnu_strftime.c:567]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:890]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:1161]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:1232]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:663]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:678]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:689]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:704]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:843]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [compat\gnu_strftime.c:959]: (style) Found obsolete function 'bcopy'. It is recommended that new applications use the 'memmove' function
 [mod\compress.mod\compress.c:101]: (error) Resource leak: fin
 [mod\compress.mod\compress.c:243]: (error) Resource leak: fin
 [mod\filesys.mod\files.c:1411]: (error) Uninitialized variable: destdir
 [mod\server.mod\server.c:385]: (error) Possible null pointer dereference: rest
 [mod\uptime.mod\uptime.c:127]: (style) Found obsolete function 'gethostbyname'. It is recommended that new applications use the 'getnameinfo' function
 [mod\uptime.mod\uptime.c:196]: (style) Variable 'server_funcs' is assigned a value that is never used

**Comment by thommey** [comment]
**Comment by @Pixelz**
This needs more research to determine if these are actual problems.

**Comment by Cizzle** [comment]
So I've rechecked the src/ with an updated cppcheck (1.76.1 dating from Oct 2016) as the last check dates from already 6 years ago.

Results:
~~[botcmd.c:328]: (error) Undefined behavior: Variable 's' is used as parameter and destination in s[n]printf().~~ fixed by #305 
[compat/gnu_strftime.c:728]: (error) Null pointer dereference
~~[mem.c:378]: (error) Memory leak: x~~ fixed by #306
~~[mod/channels.mod/tclchan.c:1112]: (error) syntax error~~ False positive
~~[mod/compress.mod/compress.c:100]: (error) Resource leak: fin~~ fixed by #306
~~[mod/compress.mod/compress.c:244]: (error) Resource leak: fin~~ fixed by #306
~~[mod/filesys.mod/files.c:285]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/filesys.mod/files.c:368]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/filesys.mod/files.c:739]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/filesys.mod/files.c:1135]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/filesys.mod/files.c:1400]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/filesys.mod/tclfiles.c:472]: (error) Converting pointer arithmetic result to bool. The bool is always true unless there is undefined behaviour.~~ False positive
~~[mod/share.mod/share.c:1321]: (error) Array 'C_share[40]' accessed at index 9998, which is out of bounds.~~ False positive
~~[mod/transfer.mod/transfer.c:1027]: (error) Resource leak: f~~ fixed by #306
~~[net.c:258]: (error) Uninitialized variable: h~~ fixed by #306

I haven't touched the gnu_strftime one in compat as this might be obsolete anyway.

**Comment by vanosg** [comment]
Mem.c is being addressed in a separate commit (coverity)
