### ISSUE TITLE
eggdrop1.8.4 compiling error

### ISSUE THREAD

**Issue by Jokah** [eggheads/eggdrop#801]
I encountered this issue while compiling on a Debian 9:

make[2]: Leaving directory '/root/eggdrop-1.8.4/src'
make[2]: Entering directory '/root/eggdrop-1.8.4/src'
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include/tcl8.6 -o ../eggdrop bg.o botcmd.o botmsg.o botnet.o chanprog.o cmds.o dcc.o dccutil.o dns.o flags.o language.o match.o main.o mem.o misc.o misc_file.o modules.o net.o rfc1459.o tcl.o tcldcc.o tclhash.o tclmisc.o tcluser.o tls.o userent.o userrec.o users.o  -L/usr/lib/x86_64-linux-gnu -ltcl8.6  -lz -lpthread -lieee -lm -lssl -lcrypto -ldl  md5/md5c.o compat/*.o `cat mod/mod.xlibs`
/usr/bin/ld: cannot find -lieee
collect2: error: ld returned 1 exit status
Makefile:44: recipe for target 'link' failed
make[2]: *** [link] Error 1
make[2]: Leaving directory '/root/eggdrop-1.8.4/src'
Makefile:53: recipe for target '../eggdrop' failed
make[1]: *** [../eggdrop] Error 2
make[1]: Leaving directory '/root/eggdrop-1.8.4/src'
Makefile:243: recipe for target 'eggdrop' failed
make: *** [eggdrop] Error 2

**Comment by thommey** [comment]
This seems to be the same issue as mentioned on [https://www.linuxquestions.org/questions/slackware-14/tcl-linking-library-not-found-4175623418/](url). Our Tcl autoconfig (tcl.m4 from TEA) adds -lieee unconditionally when it shouldn't. Upstream has removed it because it hasn't been necessary since at least Tcl8.4.

As a fix (and something for you to test if you want), you can remove the line
`    AC_CHECK_LIB(ieee, main, [MATH_LIBS="-lieee $MATH_LIBS"])`
from m4/tcl.m4, then run `misc/runautotools` (`apt-get install autoconf` might be required), and start over with `make distclean` followed by the usual `./configure`.

Thanks for the report, we'll discuss how we are going to address this as soon as possible.

**Comment by thommey** [comment]
Could you let us know which Debian version it is exactly? It's in /etc/debian_version
And you can try to upgrade your system (apt-get update && apt-get upgrade) to make sure you have the latest Tcl8.6 and libc6-dev packages.

**Comment by Jokah** [comment]
The version is written in my first line from my previous post, anyway:

cat /etc/debian_version
9

apt-cache policy tcl8.6
tcl8.6:
  Installed: 8.6.6+dfsg-1+b1

apt-cache policy tcl-dev
tcl-dev:
  Installed: 8.6.0+9

**Comment by thommey** [comment]
Thanks. A few more came to mind:

1. /lib/x86_64-linux-gnu/libc.so.6
2. find /usr -name "libieee.*" 2>/dev/null
3. find /usr -name tclConfig.sh 2>/dev/null
4. find /usr -name tclConfig.sh 2>/dev/null | xargs grep TCL_LIBS
5. dpkg -l | grep tcl
6. dpkg -l | grep libc6

(or apt-cache policy libc6-dev, libc6, tcl, tcl8.6-dev, tcl8.6)

**Comment by thommey** [comment]
The issue has to do with the glibc version and the Tcl version mismatching.

glibc before 2.27 provided a dummy "libieee.a" that could be linked against with -lieee, even though it has no effect. That was changed in 2.27. Both Tcl and Eggdrop only add -lieee to the linker flags if it exists.

Eggdrop does this on ./configure, so a fresh ./configure fixes that part, and we can rule that out.

Tcl does it on compilation and writes the result to tclConfig.sh, which Eggdrop loads and uses. So a "stale" tclConfig.sh can cause this, but only if you upgrade libc6-dev to a newer version without upgrading tcl8.6-dev to the correspondig version from Debian. On Debian stable, you should have libieee.a in /usr/lib/x86_64-linux-gnu (or /usr/lib), because the libc6-dev package provides it.

(Sorry I deleted my earlier comments, I wanted to try to bring our questions into a better list format, but you answered in between :)

So the libc versions from the last comment etc. would help to debug this. Thanks.

**Comment by Jokah** [comment]
1. /lib/x86_64-linux-gnu/libc.so.6 
GNU C Library (Debian GLIBC 2.27-5) stable release version 2.27.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 7.3.0.
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.

2. find /usr -name "libieee.*" 2>/dev/null
it doesn't return any result

3. find /usr -name tclConfig.sh 2>/dev/null
/usr/lib/x86_64-linux-gnu/tclConfig.sh
/usr/lib/x86_64-linux-gnu/tcl8.6/tclConfig.sh
/usr/lib/tclConfig.sh
/usr/lib/tcl8.6/tclConfig.sh

4.  find /usr -name tclConfig.sh 2>/dev/null | xargs grep TCL_LIBS
/usr/lib/x86_64-linux-gnu/tclConfig.sh:TCL_LIBS='-ldl -lz  -lpthread -lieee -lm'
/usr/lib/x86_64-linux-gnu/tcl8.6/tclConfig.sh:TCL_LIBS='-ldl -lz  -lpthread -lieee -lm'

5. dpkg -l | grep tcl
ii  libtcl8.6:amd64                                             8.6.6+dfsg-1+b1                                          amd64        Tcl (the Tool Command Language) v8.6 - run-time library files
ii  mysqltcl                                                    3.052-2                                                  amd64        interface to the MySQL database for the Tcl language
ii  tcl                                                         8.6.0+9                                                  amd64        Tool Command Language (default version) - shell
ii  tcl-dev:amd64                                               8.6.0+9                                                  amd64        Tool Command Language (default version) - development files
ii  tcl8.6                                                      8.6.6+dfsg-1+b1                                          amd64        Tcl (the Tool Command Language) v8.6 - shell
ii  tcl8.6-dev:amd64                                            8.6.6+dfsg-1+b1                                          amd64        Tcl (the Tool Command Language) v8.6 - development files

6. dpkg -l | grep libc6
ii  libc6:amd64                                                 2.27-5                                                   amd64        GNU C Library: Shared libraries
ii  libc6-dbg:amd64                                             2.27-5                                                   amd64        GNU C Library: detached debugging symbols
ii  libc6-dev:amd64                                             2.27-5                                                   amd64        GNU C Library: Development Libraries and Header Files

**Comment by thommey** [comment]
Okay. So, I don't know how you ended up with the libc6 package in version 2.27 on that system, but Debian stable is still at 2.24-11. Could have been a partial migration/mix to testing instead of stable, perhaps. The realistic options I see are:

- Upgrade your whole system to Debian testing
- Selectively install the tcl8.6-dev package from Debian testing, if it doesn't entail too many complex dependencies that would end up upgrading your whole system
- Compile Tcl yourself, either system-wide or as your Eggdrop useraccount, then ./configure eggdrop again (possibly with --with-tcl=/folder/containing/tclConfig.sh/)
- Manually edit /usr/lib/x86_64-linux-gnu/tclConfig.sh and remove -lieee from TCL_LIBS (overwritten by package upgrade)
- after ./configure, edit Makefile in the main directory of Eggdrop and remove -lieee from both TCLLIB= and XLIBS= (will be overwritten by ./configure)

And the shorter summary of the issue is: Your tcl8.6(-dev) packages aren't made to work with your libc version, it's neither "both from Debian stable" nor "both from Debian testing".

**Comment by Jokah** [comment]
I guess I have a mixed stable with testing due, I have a few selected software I want to keep use as newer version (kernel and firewall at most), so I guess I either have to downgrade libc6 or upgrade libc6 to solve this, thanks.

**Comment by thommey** [comment]
downgrade libc6 or upgrade tcl8.6-dev

from my personal experience I'd advise against trying to downgrade anything on Debian without a good backup :)
