### ISSUE TITLE
Remove --disable-tls ?

### ISSUE THREAD

**Issue by vanosg** [eggheads/eggdrop#834]
The original SSL/TLS code was added to Eggdrop in 2010- nearly a decade ago. A lot has changed since then! When first introduced, TLS was not as common, or known to be as necessary, as it is now. Users were offered the option to disable TLS due to issues connecting with other botnets in certain circumstances, as well as not every machine having TLS dev libs installed to compile against- hence Eggdrop's ability to disable TLS functionality if the TLS libs were not detected, or a user intentionally disabled them with --disable-tls during configure. TLS is not *required* for Eggdrop to connect to an IRC server and function in a near-full capacity, and users may not have the permissions needed to install the TLS dev libraries on a machine.

As TLS adaption has become more prevalent, and as the Eggdrop TLS codebase has stabilized, has the time come to remove the option for --disable-tls ? I want to be clear, this is not removing the ability for eggdrop to compile without TLS libs, but if they are present on the system, to require their usage?

I'd like to open this up for discussion- I don't want to force something on the users because 'we' think it is better for them, but at the same time I think the argument for enabling a manual disabling of TLS is starting to lose some of its strength. What do you think? Is it time to remove --disable-tls ?

**Comment by michaelortmann** [comment]
I vote to remove --disable-tls. I would additionally switch openssl configure (from --with-sslinc and --with-ssllib) to ax_check_openssl.m4.

**Comment by thommey** [comment]
I disagree.

We should not impose a SSL-compilation with openssl simply because we find it, just as we don't force a NOSSL-one without it if we don't (that's what --with-ssl is for), Users might not have control over installed libraries and as long as we don't have a strict hard requirement for openssl, it should be possible to manually deactivate pulling that dependency in.

That is standard practice for configure scripts that pull in/link against dependencies and makes custom eggdrop packages, cross-compiling and other things easier and as expected by people compiling it.

The ./configure options aren't a collection of feature-switches we deem relevant/interesting, but more of a standard process of exposing our internal options (or results from auto-finding dependencies) without any subjective interpretation of what's useful for users or not. It can additionally include switches we deem useful, but not remove ones that are then hidden.

**Comment by thommey** [comment]
Integrating ax_check_openssl.m4 would be fine though, under the constraint that it can be disabled.

**Comment by michaelortmann** [comment]
pbkdf2 will need openssl, so in some distant future, we will talk about this again ;)
