### ISSUE TITLE
nickchanges require mode-tracking

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#94]
| Trac | Data |
| --: | :-- |
| Ticket | 94 |
| Reported by | assassin |
| Status | new |
| Component | Core |
| Priority | minor |
| Milestone | 1.8.0 |
| Version | 1.8.0 CVS |

if someone is flagged +a eggdrop fails to auto-op them if they change nick a few seconds after joining the chan (with aop-delay, most likely)

**Comment by bdrewery** [comment]
## src/mod/irc.mod/irc.c

### gotnick

<pre>
/* don't fill the serverqueue with modes or kicks in a nickflood */
if (chan_sentkick(m) || chan_sentdeop(m) || chan_sentop(m) ||
    chan_sentdehalfop(m) || chan_senthalfop(m) || chan_sentdevoice(m) ||
    chan_sentvoice(m))
  m->flags |= STOPCHECK;
/* Any pending kick or mode to the old nick is lost. */
m->flags &= ~(SENTKICK | SENTDEOP | SENTOP | SENTDEHALFOP | SENTHALFOP |
              SENTVOICE | SENTDEVOICE);
/* nick-ban or nick is +k or something? */
if (!chan_stopcheck(m)) {
  get_user_flagrec(m->user ? m->user : get_user_by_host(s1), &fr,
                   chan->dname);
  check_this_member(chan, m->nick, &fr);
}
</pre>

This code is removing the pending SENTOP (and SENTVOICE and SENTHALFOP) for the user if they change their nick before receiving the delayed mode.

It's also never clearing the `STOPCHECK` flag so if the user changes nick again without pending modes it will not call `check_this_member` on them.

The simplest fix is removing the `STOPCHECK` set/check entirely (and keeping the SENT removals). Then the user will be rechecked.

**Comment by michaelortmann** [comment]
we should not simply remove the nick flood protection. and i guess, that's why this old issue is still open.

we could try to replace the old nick with the new nick for the sentop within the server queue, but this seems no easy thing to do, i still lack the understanding of eggdrops server queue implementation, and its unclear if this will even work out. currently it looks, like eggdrop can only add to its queue.

we could also implement that eggdrop memorizes the last time of check_this_member() call for any member and if a certain amount of time passed and STOPCHECK is set, we could call check_this_member() and reset STOPCHECK. we could replace STOPCHECK with a time value. if its not set, it would mean, no STOPCHECK, nothing to do. if its set, we would wait until the current time maches, and then clear it and call check_this_member(). if a new nick change comes in between, the time value will be updated.
