### ISSUE TITLE
Difficulty connecting two eggdrop 1.8.4 bots using TLS

### ISSUE THREAD

**Issue by LimeyTX** [eggheads/eggdrop#971]
I created two bots, let's call them hub and leaf. They are on different servers. I created via .+bot on each bot a reference to the other and I did .link and they linked. Anything I typed on one bot appeared on the other bot of the botnet as you would expect. I then unlinked the two bots.

Both bots have an eggdrop.key and eggdrop.crt made using "make sslcert".

So then on the leaf I typed
```
.botattr hub +hp
.botattr hub |s #chan
``` 

and on hub I typed
```
.botattr leaf +s
.botattr leaf |s #chan
```
and, as I expected, hub tried to link to leaf and the following appeared on leaf.

```
Got STARTTLS from hub. Replying...
STARTTLS failed while linking to hub
Received challenge from hub.. sending response ...
Lost Bot: hub
```

Can anyone give me a clue as to what is going on? The fact that they linked correctly BEFORE the botattr was set but not after doesn't make any sense to me.

**Comment by vanosg** [comment]
Hi LimeyTx, thanks for writing in- we tend to use the issues forum here for bug tracking rather than troubleshooting. If you join #eggdrop on Freenode, you'll find help more quickly and thoroughly available there. If this is indeed a bug, we'll reopen the issue. Thanks, and look forward to seeing you in the channel.

**Comment by LimeyTX** [comment]
Sorry. I have tried #eggdrop on EFNet and Undernet and got no help at all in either. I am sure I will figure it out in time.
